export let pictures = [
  "https://res.cloudinary.com/deckhnump/image/upload/v1717240360/artist2_gerp3h.jpg",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717240360/artist_qjs8rk.jpg",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238495/op_dtlcxk.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238495/f_qfxg1b.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238494/rtr_q7cd8u.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238494/lmkm_cwiiig.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238493/lkl_hpinhq.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238491/dd_na85no.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238491/l_m2rgna.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238491/g_ol1xtx.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238490/ewr_f0trvd.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238488/asdf_viwe6i.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238487/as_ilr4d1.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238487/b_ckcimu.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238487/c_rmkgft.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238485/aa_fbgbhw.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238485/17_ihaqif.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238485/7_xdbdvr.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238484/9_q4rbku.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238483/a_kpx1xf.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238483/8_vbnhmx.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238483/6_iyfxs7.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238481/10_mwe5rb.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238480/2_fengbi.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238480/1_tg36cw.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238480/5_yhreaj.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238478/3_mnzzfk.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717238478/4_wzaph2.png",
  "https://res.cloudinary.com/deckhnump/image/upload/v1717198556/pianist_bvudci.jpg"
]

export let users = [
  { 
    isArtist: true,
    name: "Emma Müller",
    moreThanOne: false,
    email: "emma@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Blues singer",
    artistFee: "100",
    artistVideos: "",
    artistWebsite: "",
    artistGenre: ""
  }, 
  {
    isArtist: true,
    name: "Lars Weber",
    moreThanOne: false,
    email: "lars@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Classical pianist",
    artistFee: "150",
    artistVideos: "https://videos.com/larsweber",
    artistWebsite: "https://larsweber.com",
    artistGenre: "Classical"
  },
  {
    isArtist: true,
    name: "Nina Schmidt",
    moreThanOne: false,
    email: "nina@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Abstract painter",
    artistFee: "200",
    artistVideos: "https://videos.com/ninaschmidt",
    artistWebsite: "https://ninaschmidtart.com",
    artistGenre: "Abstract Art"
  },
  {
    isArtist: true,
    name: "Johannes Becker",
    moreThanOne: false,
    email: "johannes@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Jazz saxophonist",
    artistFee: "250",
    artistVideos: "https://videos.com/johannesbecker",
    artistWebsite: "https://johannesbeckerjazz.com",
    artistGenre: "Jazz"
  },
  {
    isArtist: true,
    name: "Laura Fischer",
    moreThanOne: false,
    email: "laura@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Modern dancer",
    artistFee: "180",
    artistVideos: "https://videos.com/laurafischer",
    artistWebsite: "https://laurafischer.com",
    artistGenre: "Dance"
  },
  {
    isArtist: true,
    name: "Felix Braun",
    moreThanOne: false,
    email: "felix@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Rock guitarist",
    artistFee: "220",
    artistVideos: "https://videos.com/felixbraun",
    artistWebsite: "https://felixbraunrock.com",
    artistGenre: "Rock"
  },
  {
    isArtist: true,
    name: "Sara Klein",
    moreThanOne: false,
    email: "sara@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Contemporary sculptor",
    artistFee: "300",
    artistVideos: "https://videos.com/saraklein",
    artistWebsite: "https://sarakleinart.com",
    artistGenre: "Sculpture"
  },
  {
    isArtist: true,
    name: "Tim Wagner",
    moreThanOne: false,
    email: "tim@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Hip-hop dancer",
    artistFee: "210",
    artistVideos: "https://videos.com/timwagner",
    artistWebsite: "https://timwagnerdance.com",
    artistGenre: "Hip-hop"
  },
  {
    isArtist: true,
    name: "Hannah Krüger",
    moreThanOne: false,
    email: "hannah@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Indie folk singer",
    artistFee: "190",
    artistVideos: "https://videos.com/hannahkrueger",
    artistWebsite: "https://hannahkruegerfolk.com",
    artistGenre: "Indie Folk"
  },
  {
    isArtist: true,
    name: "Oliver Richter",
    moreThanOne: false,
    email: "oliver@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Electronic music producer",
    artistFee: "270",
    artistVideos: "https://videos.com/oliverrichter",
    artistWebsite: "https://oliverrichterbeats.com",
    artistGenre: "Electronic"
  },
  {
    isArtist: true,
    name: "Mia König",
    moreThanOne: false,
    email: "mia@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Pop singer-songwriter",
    artistFee: "230",
    artistVideos: "https://videos.com/miakoenig",
    artistWebsite: "https://miakoenigpop.com",
    artistGenre: "Pop"
  },
  {
    isArtist: true,
    name: "Max Bauer",
    moreThanOne: false,
    email: "max@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Street artist",
    artistFee: "260",
    artistVideos: "https://videos.com/maxbauer",
    artistWebsite: "https://maxbauerart.com",
    artistGenre: "Street Art"
  },
  {
    isArtist: true,
    name: "Lea Hartmann",
    moreThanOne: false,
    email: "lea@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Opera singer",
    artistFee: "280",
    artistVideos: "https://videos.com/leahartmann",
    artistWebsite: "https://leahartmannopera.com",
    artistGenre: "Opera"
  },
  {
    isArtist: true,
    name: "Jonas Vogel",
    moreThanOne: false,
    email: "jonas@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Contemporary photographer",
    artistFee: "240",
    artistVideos: "https://videos.com/jonasvogel",
    artistWebsite: "https://jonasvogelphoto.com",
    artistGenre: "Photography"
  },
  {
    isArtist: true,
    name: "Anna Schulz",
    moreThanOne: false,
    email: "anna@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Jazz singer",
    artistFee: "170",
    artistVideos: "https://videos.com/annaschulz",
    artistWebsite: "https://annaschulzjazz.com",
    artistGenre: "Jazz"
  },
  {
    isArtist: true,
    name: "Lena Meier",
    moreThanOne: false,
    email: "lena@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Experimental filmmaker",
    artistFee: "320",
    artistVideos: "https://videos.com/lenameier",
    artistWebsite: "https://lenameierfilm.com",
    artistGenre: "Film"
  },
  {
    isArtist: true,
    name: "Paul Neumann",
    moreThanOne: false,
    email: "paul@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Classical violinist",
    artistFee: "200",
    artistVideos: "https://videos.com/paulneumann",
    artistWebsite: "https://paulneumannviolin.com",
    artistGenre: "Classical"
  },
  {
    isArtist: true,
    name: "Clara Weiß",
    moreThanOne: false,
    email: "clara@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Indie rock drummer",
    artistFee: "250",
    artistVideos: "https://videos.com/claraweiss",
    artistWebsite: "https://claraweissdrums.com",
    artistGenre: "Indie Rock"
  },
  {
    isArtist: true,
    name: "David Horn",
    moreThanOne: false,
    email: "david@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Spoken word poet",
    artistFee: "180",
    artistVideos: "https://videos.com/davidhorn",
    artistWebsite: "https://davidhornpoetry.com",
    artistGenre: "Spoken Word"
  },
  {
    isArtist: true,
    name: "Ella Schwarz",
    moreThanOne: false,
    email: "ella@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Folk guitarist",
    artistFee: "210",
    artistVideos: "https://videos.com/ellaschwarz",
    artistWebsite: "https://ellaschwarzfolk.com",
    artistGenre: "Folk"
  },
  {
    isArtist: true,
    name: "Tom Hofmann",
    moreThanOne: false,
    email: "tom@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Jazz trumpeter",
    artistFee: "220",
    artistVideos: "https://videos.com/tomhofmann",
    artistWebsite: "https://tomhofmannjazz.com",
    artistGenre: "Jazz"
  },
  {
    isArtist: true,
    name: "Maria Seidel",
    moreThanOne: false,
    email: "maria@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Digital artist",
    artistFee: "260",
    artistVideos: "https://videos.com/mariaseidel",
    artistWebsite: "https://mariaseideldigital.com",
    artistGenre: "Digital Art"
  },
  {
    isArtist: true,
    name: "Jan Richter",
    moreThanOne: false,
    email: "jan@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Classical cellist",
    artistFee: "230",
    artistVideos: "https://videos.com/janrichter",
    artistWebsite: "https://janrichtercello.com",
    artistGenre: "Classical"
  },
  {
    isArtist: true,
    name: "Sophia Kruger",
    moreThanOne: false,
    email: "sophia@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Graffiti artist",
    artistFee: "270",
    artistVideos: "https://videos.com/sophiakruger",
    artistWebsite: "https://sophiakrugerart.com",
    artistGenre: "Graffiti"
  },
  {
    isArtist: true,
    name: "Erik Lange",
    moreThanOne: false,
    email: "erik@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Ballet dancer",
    artistFee: "280",
    artistVideos: "https://videos.com/eriklange",
    artistWebsite: "https://eriklangeballet.com",
    artistGenre: "Ballet"
  },
  {
    isArtist: true,
    name: "Lina Braun",
    moreThanOne: false,
    email: "lina@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Jazz bassist",
    artistFee: "250",
    artistVideos: "https://videos.com/linabraun",
    artistWebsite: "https://linabraunjazz.com",
    artistGenre: "Jazz"
  },
  {
    isArtist: true,
    name: "Chris Walter",
    moreThanOne: false,
    email: "chris@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Film composer",
    artistFee: "300",
    artistVideos: "https://videos.com/chriswalter",
    artistWebsite: "https://chriswalterfilm.com",
    artistGenre: "Film Music"
  },
  {
    isArtist: true,
    name: "Isabel Hoffmann",
    moreThanOne: false,
    email: "isabel@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Indie singer",
    artistFee: "190",
    artistVideos: "https://videos.com/isabelhoffmann",
    artistWebsite: "https://isabelhoffmannindie.com",
    artistGenre: "Indie"
  },
  {
    isArtist: true,
    name: "Günther B.",
    moreThanOne: false,
    email: "guntherb@artist.com",
    password: "Hello1",
    picture: "",
    city: "Berlin",
    artistDescription: "Folk german music",
    artistFee: "190",
    artistVideos: "https://videos.com/ottob",
    artistWebsite: "https://ottob.com",
    artistGenre: "Folk"
  }
]



/*
Atlacho: 

 isArtist: true,
    name: "Johannes",
    moreThanOne: false,
    email: "emma@artist.com",
    password: "Hello1",
    picture: "https://res.cloudinary.com/deckhnump/image/upload/v1717194936/movie-gallery/xilk8q3wplgrzpcgeuav.jpg",
    city: 'Berlin',
    artistDescription: 'I have to work some extra hours to provide for my 17 kinder. Please help me. I wil be famous in the future',
    artistFee: '100',
    artistVideos: '',
    artistWebsite: '',
    artistGenre: ''
*/